name: project_llm
channels:
  - nvidia
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pytorch==2.5.1
  - torchvision==0.20.1
  - torchaudio==2.5.1
  - cudatoolkit=11.8.0
  - numpy==1.26.4
  - pip:
    - transformers==4.51.3
    - sentence-transformers==2.5.1
    - peft==0.14.0
    - bitsandbytes==0.45.3
    - faiss-cpu==1.10.0
    - datasets==3.3.2
    - huggingface-hub==0.30.2
    - accelerate==1.4.0
    - autogen==0.7.6
    - spacy==3.8.4
    - pandas==2.2.3
    - tqdm==4.67.1
    - matplotlib==3.10.1
    - seaborn==0.13.2
    - python-dotenv==1.0.1
