[MISSING_PAGE_FAIL:1]

[MISSING_PAGE_EMPTY:94]

[MISSING_PAGE_EMPTY:95]

[MISSING_PAGE_EMPTY:96]

\(g_{i:k}g_{i:k}g_{i:k}^{H}=R_{u}(0,0)\). Because of \(R_{u}(0,0)\neq 0\) for binary, ternary or polyphase sequences, we obtain rank of matrix \(GG^{H}\):

\[\text{rank}\left(GG^{H}\right)\to MT_{i}T_{2}\]

After employing inequality on rank:

\[\text{rank}\left(GG^{H}\right)\leq\text{number of columns of matrix G}\]

we proclaim the following theorem.

_Theorem_ To a binary, ternary or polyphase CZCE(\((L_{1},L_{2})\),M.(\(T_{1},T_{2})\)),

\[MT_{i}T_{2}\leq 2(L_{1}+T_{1}-1)(L_{2}+T_{2}-1)\]

## 4 Discussions and Conclusions

i) We consider a special case: \(L_{1}=1\), then \(T_{1}=1\) and our 2-D sequence set degenerates to 1-D one, the corresponding lower bound is \(MT_{2}\leq 2(L_{2}+T_{2}-1)\), which is exactly the lower bound proposed by Xu, et al [4] for 1-D ternary sequences

ii) For another special case: \(L_{1}=T_{1}\) and \(L_{2}=T_{2}\), our lower bound shows that M-8, this means that family size of Luke's sequence set is small.

iii) Conclusion ii) shows that 2-D GCOSS with ZCZ in UWB techniques is more qualified than 2-D complementary sequence set.

## References

[1]FOROUZAN,A.R., MASOUMEH,N.K. and SALEHI,J.A.: "Performance analysis of ultra wide-band time-hopping code division multiple access systems: uncode and code' schemes'. _In Proc. of IEEE International Conference on Communications (IEEE ICC2001)_, June 11-14, 2001, pp.3017-3021

[2]ZHANG,C., LIN,X. and HATORI, M.: 'Novel Two Dimensional Complementary Sequences in Ultra Wideband Wireless Communications'. _In Proc. of 2nd IEEE Conference on Ultra Wideband Systems and Technologies (IEEE UWBST2003)_, November 16-19, 2003, Virginia, USA

[3]LOKE,H.D.: 'Sets of one and higher dimensional Welti codes and complementary codes'. _IEEE Transactions on Aerospace and Electronic Systems_, 1985, AES-21,No.2, pp.170-179

[4]XU,S.J. and L,J,D.B.: 'Ternary complementary orthogonal sequences with zero correlation window'. _In Proc. of the 14\({}^{A}\) IEEE international symposium on personal, indoor and mobile radio communications (IEEE PIMRC 2003)_, September 7-10, 2003, Beijing, China